In [1]:
import gc

gc.collect()

14

# elevator-rmnd-lstm

Use the simulated dataset generated by `dataset.py` to train
regression models, in order to predict the remaining useful life (RUL)
of lifts.

**This approach uses an LSTM.**

In [ ]:
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

!pip install wandb weave pytorch_lightning torchmetrics
!wandb login --relogin

sns.set_theme(context="notebook", style="ticks")

Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (0.27.1)
Collecting weave
  Downloading weave-0.52.42-py3-none-any.whl.metadata (25 kB)
Collecting pytorch_lightning
  Downloading pytorch_lightning-2.6.5-py3-none-any.whl.metadata (21 kB)
Collecting torchmetrics
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: click>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (8.4.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (3.1.50)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from wandb) (26.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb) (4.10.0)
Requirement already satisfied: protobuf!=5.28.0,!=5.29.0,<8,>4.21.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.6 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from wandb) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.32.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.61.1)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.12/dist-packages (from wandb) (4.15.0)
Requirement already satisfied: cachetools>=6.2.4 in /usr/local/lib/python3.12/dist-packages (from weave) (6.2.6)
Collecting diskcache-weave==5.6.3.post1 (from weave)
  Downloading diskcache_weave-5.6.3.post1-py3-none-any.whl.metadata (20 kB)
Collecting gql>=3.0.0 (from gql[httpx]>=3.0.0->weave)
  Downloading gql-4.0.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: jsonschema>=4.23.0 in /usr/local/lib/python3.12/dist-packages (from weave) (4.26.0)
Requirement already satisfied: opentelemetry-api>=1.28.0 in /usr/local/lib/python3.12/dist-packages (from weave) (1.38.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-http>=1.28.0 in /usr/local/lib/python3.12/dist-packages (from weave) (1.38.0)
Requirement already satisfied: opentelemetry-sdk>=1.28.0 in /usr/local/lib/python3.12/dist-packages (from weave) (1.38.0)
Collecting opentelemetry-semantic-conventions>=0.63b0 (from weave)
  Downloading opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl.metadata (2.4 kB)
Collecting polyfile-weave>=0.5.9 (from weave)
  Downloading polyfile_weave-0.5.9-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: tenacity!=8.4.0,>=8.3.0 in /usr/local/lib/python3.12/dist-packages (from weave) (9.1.4)
Requirement already satisfied: torch>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from pytorch_lightning) (2.11.0+cu128)
Requirement already satisfied: tqdm>=4.57.0 in /usr/local/lib/python3.12/dist-packages (from pytorch_lightning) (4.67.3)
Requirement already satisfied: fsspec>=2022.5.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2022.5.0->pytorch_lightning) (2025.3.0)
Collecting lightning-utilities>=0.10.0 (from pytorch_lightning)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: numpy>1.20.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2022.5.0->pytorch_lightning) (3.14.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Collecting graphql-core<3.3,>=3.2 (from gql>=3.0.0->gql[httpx]>=3.0.0->weave)
  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: yarl<2.0,>=1.6 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (1.24.2)
Collecting backoff<3.0,>=1.11.1 (from gql>=3.0.0->gql[httpx]>=3.0.0->weave)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: anyio<5,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (4.13.0)
Requirement already satisfied: httpx<1,>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from gql[httpx]>=3.0.0->weave) (0.28.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (2026.5.1)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.28.0->weave) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-http>=1.28.0->weave) (1.75.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.38.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-http>=1.28.0->weave) (1.38.0)
Requirement already satisfied: opentelemetry-proto==1.38.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-http>=1.28.0->weave) (1.38.0)
INFO: pip is looking at multiple versions of opentelemetry-sdk to determine which version is compatible with other requirements. This could take a while.
Collecting opentelemetry-exporter-otlp-proto-http>=1.28.0 (from weave)
  Downloading opentelemetry_exporter_otlp_proto_http-1.42.1-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk>=1.28.0 (from weave)
  Downloading opentelemetry_sdk-1.42.1-py3-none-any.whl.metadata (1.7 kB)
Collecting opentelemetry-api>=1.28.0 (from weave)
  Downloading opentelemetry_api-1.42.1-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-exporter-otlp-proto-common==1.42.1 (from opentelemetry-exporter-otlp-proto-http>=1.28.0->weave)
  Downloading opentelemetry_exporter_otlp_proto_common-1.42.1-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.42.1 (from opentelemetry-exporter-otlp-proto-http>=1.28.0->weave)
  Downloading opentelemetry_proto-1.42.1-py3-none-any.whl.metadata (2.3 kB)
Collecting abnf~=2.2.0 (from polyfile-weave>=0.5.9->weave)
  Downloading abnf-2.2.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: chardet>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (5.2.0)
Collecting cint>=1.0.0 (from polyfile-weave>=0.5.9->weave)
  Downloading cint-1.0.0-py3-none-any.whl.metadata (511 bytes)
Collecting fickling>=0.0.8 (from polyfile-weave>=0.5.9->weave)
  Downloading fickling-0.1.11-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.29.1)
Requirement already satisfied: graphviz>=0.20.1 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (0.21)
Collecting intervaltree>=2.4.0 (from polyfile-weave>=0.5.9->weave)
  Downloading intervaltree-3.2.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: jinja2>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.1.6)
Collecting kaitaistruct>=0.11 (from polyfile-weave>=0.5.9->weave)
  Downloading kaitaistruct-0.11-py2.py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: networkx>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.6.1)
Requirement already satisfied: Pillow>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (11.3.0)
Collecting pdfminer.six>=20251230 (from polyfile-weave>=0.5.9->weave)
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.6->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.6->wandb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.6->wandb) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2026.5.20)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch_lightning) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch_lightning) (1.14.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch_lightning) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch_lightning) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch_lightning) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch_lightning) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch_lightning) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch_lightning) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.1.0->pytorch_lightning) (12.8.90)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (0.5.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.1.0->pytorch_lightning) (1.5.5)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.27.0->gql[httpx]>=3.0.0->weave) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.27.0->gql[httpx]>=3.0.0->weave) (0.16.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from intervaltree>=2.4.0->polyfile-weave>=0.5.9->weave) (2.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.1.0->polyfile-weave>=0.5.9->weave) (3.0.3)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (48.0.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.1.0->pytorch_lightning) (1.3.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.28.0->weave) (4.1.0)
Downloading weave-0.52.42-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 45.0 MB/s eta 0:00:00
Downloading diskcache_weave-5.6.3.post1-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.9/45.9 kB 3.2 MB/s eta 0:00:00
Downloading pytorch_lightning-2.6.5-py3-none-any.whl (852 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 44.6 MB/s eta 0:00:00
Downloading torchmetrics-1.9.0-py3-none-any.whl (983 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 39.8 MB/s eta 0:00:00
Downloading gql-4.0.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 4.4 MB/s eta 0:00:00
Downloading lightning_utilities-0.15.3-py3-none-any.whl (31 kB)
Downloading opentelemetry_sdk-1.42.1-py3-none-any.whl (170 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 8.9 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 10.1 MB/s eta 0:00:00
Downloading opentelemetry_api-1.42.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 2.8 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_http-1.42.1-py3-none-any.whl (21 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.42.1-py3-none-any.whl (17 kB)
Downloading opentelemetry_proto-1.42.1-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 3.0 MB/s eta 0:00:00
Downloading polyfile_weave-0.5.9-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 34.7 MB/s eta 0:00:00
Downloading abnf-2.2.0-py3-none-any.whl (39 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading cint-1.0.0-py3-none-any.whl (5.6 kB)
Downloading fickling-0.1.11-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.5/58.5 kB 1.9 MB/s eta 0:00:00
Downloading graphql_core-3.2.11-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.9/214.9 kB 10.2 MB/s eta 0:00:00
Downloading intervaltree-3.2.1-py2.py3-none-any.whl (25 kB)
Downloading kaitaistruct-0.11-py2.py3-none-any.whl (11 kB)
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 41.0 MB/s eta 0:00:00
Installing collected packages: opentelemetry-proto, opentelemetry-api, lightning-utilities, kaitaistruct, intervaltree, graphql-core, fickling, diskcache-weave, cint, backoff, abnf, opentelemetry-semantic-conventions, opentelemetry-exporter-otlp-proto-common, gql, pdfminer.six, opentelemetry-sdk, polyfile-weave, opentelemetry-exporter-otlp-proto-http, weave, torchmetrics, pytorch_lightning
  Attempting uninstall: opentelemetry-proto
    Found existing installation: opentelemetry-proto 1.38.0
    Uninstalling opentelemetry-proto-1.38.0:
      Successfully uninstalled opentelemetry-proto-1.38.0
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.38.0
    Uninstalling opentelemetry-api-1.38.0:
      Successfully uninstalled opentelemetry-api-1.38.0
  Attempting uninstall: opentelemetry-semantic-conventions
    Found existing installation: opentelemetry-semantic-conventions 0.59b0
    Uninstalling opentelemetry-semantic-conventions-0.59b0:
      Successfully uninstalled opentelemetry-semantic-conventions-0.59b0
  Attempting uninstall: opentelemetry-exporter-otlp-proto-common
    Found existing installation: opentelemetry-exporter-otlp-proto-common 1.38.0
    Uninstalling opentelemetry-exporter-otlp-proto-common-1.38.0:

## preprocessing
* Import the simulated dataset
* ~~Convert lift ids to integers~~ [already handled by `dataset.py`]
* ~~Compute instantaneous time derivatives of each sensor metric~~ [already handled by `dataset.py`]
* ~~Compute RUL in h~~ [already handled by `dataset.py`]
* Split data into training/testing sets
* Scale data with a `Scaler`

In [3]:
from google.colab import files
uploaded = files.upload()

FNAME = "liftdata_v4.pkl"
df_full = pd.read_pickle(FNAME)
df_full.head(10)

Saving liftdata_v3.pkl to liftdata_v3.pkl

,timestamp,lift_id,lift_model,lift_age_hours,ARM_DIST_mm,DOOR_DIST_mm,FLOOR_DIST_mm,ROPE_MFL_mV,BEARING_TEMP_C,maintenance_done,...,arm_door_ratio,floor_door_ratio,temp_x_rope,cumulative_rope_degradation,cumulative_bearing_heat,ARM_DIST_mm_per_hr,DOOR_DIST_mm_per_hr,FLOOR_DIST_mm_per_hr,ROPE_MFL_mV_per_hr,BEARING_TEMP_C_per_hr
0,2023-01-01 00:00:00,1,Otis Gen2,15000,0.480,1.996,0.028,10.045,33.693,0,...,0.240481,0.014028,338.446185,10.045,33.693,0.0000,0.0000,0.0000,0.0000,0.0000
1,2023-01-01 12:00:00,1,Otis Gen2,15012,0.527,2.065,0.144,9.681,36.860,0,...,0.255206,0.069734,356.841660,19.726,70.553,0.0039,0.0057,0.0097,-0.0303,0.2639
2,2023-01-02 00:00:00,1,Otis Gen2,15024,0.501,2.244,0.197,9.351,35.014,0,...,0.223262,0.087790,327.415914,29.077,105.567,-0.0022,0.0149,0.0044,-0.0275,-0.1538
3,2023-01-02 12:00:00,1,Otis Gen2,15036,0.498,2.031,0.208,9.458,34.025,0,...,0.245199,0.102413,321.808450,38.535,139.592,-0.0003,-0.0178,0.0009,0.0089,-0.0824
4,2023-01-03 00:00:00,1,Otis Gen2,15048,0.533,2.217,0.471,10.870,36.996,0,...,0.240415,0.212449,402.146520,49.405,176.588,0.0029,0.0155,0.0219,0.1177,0.2476
5,2023-01-03 12:00:00,1,Otis Gen2,15060,0.530,2.276,0.485,9.975,36.493,0,...,0.232865,0.213093,364.017675,59.380,213.081,-0.0003,0.0049,0.0012,-0.0746,-0.0419
6,2023-01-04 00:00:00,1,Otis Gen2,15072,0.536,2.389,0.085,9.975,36.464,0,...,0.224362,0.035580,363.728400,69.355,249.545,0.0005,0.0094,-0.0333,0.0000,-0.0024
7,2023-01-04 12:00:00,1,Otis Gen2,15084,0.556,2.166,0.446,10.252,36.737,0,...,0.256694,0.205909,376.627724,79.607,286.282,0.0017,-0.0186,0.0301,0.0231,0.0228
8,2023-01-05 00:00:00,1,Otis Gen2,15096,0.585,2.249,0.132,10.477,37.251,0,...,0.260115,0.058693,390.278727,90.084,323.533,0.0024,0.0069,-0.0262,0.0187,0.0428
9,2023-01-05 12:00:00,1,Otis Gen2,15108,0.573,2.364,0.834,11.572,36.114,0,...,0.242386,0.352792,417.911208,101.656,359.647,-0.0010,0.0096,0.0585,0.0912,-0.0948

In [4]:
# Remove unnecessary columns
df_full = df_full.drop(columns=["timestamp", "lift_model", "maintenance_done"])

# Then remove NaN values
df_full.dropna(inplace=True)

Since there exist rows that have `np.inf` as their predicted RUL, extract those rows for experimentation later on.
Retain the remaining roles (with valid RULs) for training and testing.

In [5]:
df_experimental = df_full[df_full["RUL_hrs"] == np.inf]
df_useful = df_full[df_full["RUL_hrs"] != np.inf]

# Check to see the experimental/useful split was done correctly
assert all(
    df_experimental["RUL_hrs"] == np.inf
), "All records in experimental set should have RUL_hrs == np.inf"
assert all(
    df_useful["RUL_hrs"] != np.inf
), "All records in useful set should have valid RUL_hrs"

df_useful.head(40)

,lift_id,lift_age_hours,ARM_DIST_mm,DOOR_DIST_mm,FLOOR_DIST_mm,ROPE_MFL_mV,BEARING_TEMP_C,RUL_hrs,age_since_last_maint,arm_door_ratio,floor_door_ratio,temp_x_rope,cumulative_rope_degradation,cumulative_bearing_heat,ARM_DIST_mm_per_hr,DOOR_DIST_mm_per_hr,FLOOR_DIST_mm_per_hr,ROPE_MFL_mV_per_hr,BEARING_TEMP_C_per_hr
142,1,16704,1.507,7.714,10.128,17.462,75.193,0.0,0.000000,0.195359,1.312937,1313.020166,2059.949,7925.487,0.0027,0.0016,0.0021,-0.1110,-0.0293
143,1,16716,0.492,2.087,0.079,9.907,33.291,1680.0,0.017241,0.235745,0.037853,329.813937,2069.856,7958.778,-0.0846,-0.4689,-0.8374,-0.6296,-3.4918
144,1,16728,0.483,2.071,0.005,10.555,34.098,1668.0,0.034483,0.233221,0.002414,359.904390,2080.411,7992.876,-0.0008,-0.0013,-0.0062,0.0540,0.0673
145,1,16740,0.540,2.087,0.322,10.248,35.311,1656.0,0.051724,0.258744,0.154288,361.867128,2090.659,8028.187,0.0048,0.0013,0.0264,-0.0256,0.1011
146,1,16752,0.528,2.177,0.241,10.670,34.296,1644.0,0.068966,0.242535,0.110703,365.938320,2101.329,8062.483,-0.0010,0.0075,-0.0068,0.0352,-0.0846
147,1,16764,0.528,2.187,0.183,10.131,35.045,1632.0,0.086207,0.241427,0.083676,355.040895,2111.460,8097.528,0.0000,0.0008,-0.0048,-0.0449,0.0624
148,1,16776,0.504,2.295,0.832,11.048,36.034,1620.0,0.103448,0.219608,0.362527,398.103632,2122.508,8133.562,-0.0020,0.0090,0.0541,0.0764,0.0824
149,1,16788,0.514,2.314,0.669,10.738,36.379,1608.0,0.120690,0.222126,0.289110,390.637702,2133.246,8169.941,0.0008,0.0016,-0.0136,-0.0258,0.0287
150,1,16800,0.502,2.294,0.672,11.244,34.894,1596.0,0.137931,0.218832,0.292938,392.348136,2144.490,8204.835,-0.0010,-0.0017,0.0003,0.0422,-0.1237
151,1,16812,0.538,2.218,0.837,10.575,35.182,1584.0,0.155172,0.242561,0.377367,372.049650,2155.065,8240.017,0.0030,-0.0063,0.0137,-0.0558,0.0240
152,1,16824,0.520,2.404,1.001,11.080,36.504,1572.0,0.172414,0.216306,0.416389,404.464320,2166.145,8276.521,-0.0015,0.0155,0.0137,0.0421,0.1102
153,1,16836,0.530,2.569,1.466,10.198,36.328,1560.0,0.189655,0.206306,0.570650,370.472944,2176.343,8312.849,0.0008,0.0138,0.0388,-0.0735,-0.0147
154,1,16848,0.568,2.633,1.085,10.417,38.096,1548.0,0.206897,0.215723,0.412077,396.846032,2186.760,8350.945,0.0032,0.0053,-0.0318,0.0182,0.1473
155,1,16860,0.563,2.393,1.380,10.226,34.926,1536.0,0.224138,0.235269,0.576682,357.153276,2196.986,8385.871,-0.0004,-0.0200,0.0246,-0.0159,-0.2642
156,1,16872,0.581,2.426,1.376,10.951,37.216,1524.0,0.241379,0.239489,0.567189,407.552416,2207.937,8423.087,0.0015,0.0028,-0.0003,0.0604,0.1908
157,1,16884,0.530,2.659,1.515,10.196,37.595,1512.0,0.258621,0.199323,0.569763,383.318620,2218.133,8460.682,-0.0042,0.0194,0.0116,-0.0629,0.0316
158,1,16896,0.562,2.575,1.462,9.856,38.828,1500.0,0.275862,0.218252,0.567767,382.688768,2227.989,8499.510,0.0027,-0.0070,-0.0044,-0.0283,0.1028
159,1,16908,0.560,2.554,1.722,11.137,36.307,1488.0,0.293103,0.219264,0.674236,404.351059,2239.126,8535.817,-0.0002,-0.0018,0.0217,0.1068,-0.2101
160,1,16920,0.553,2.681,1.798,10.254,40.348,1476.0,0.310345,0.206266,0.670645,413.728392,2249.380,8576.165,-0.0006,0.0106,0.0063,-0.0736,0.3367
161,1,16932,0.574,2.663,1.748,10.407,38.214,1464.0,0.327586,0.215546,0.656402,397.693098,2259.787,8614.379,0.0017,-0.0015,-0.0042,0.0128,-0.1778
162,1,16944,0.555,2.926,1.723,11.486,36.394,1452.0,0.344828,0.189679,0.588858,418.021484,2271.273,8650.773,-0.0016,0.0219,-0.0021,0.0899,-0.1517
163,1,16956,0.553,2.784,2.178,10.996,35.765,1440.0,0.362069,0.198635,0.782327,393.271940,2282.269,8686.538,-0.0002,-0.0118,0.0379,-0.0408,-0.0524
164,1,16968,0.571,2.732,2.323,11.453,38.610,1428.0,0.379310,0.209004,0.850293,442.200330,2293.722,8725.148,0.0015,-0.0043,0.0121,0.0381,0.2371
165,1,16980,0.555,2.910,2.178,11.161,38.149,1416.0,0.396552,0.190722,0.748453,425.780989,2304.883,8763.297,-0.0013,0.0148,-0.0121,-0.0243,-0.0384
166,1,16992,0.583,3.065,2.086,11.142,39.388,1404.0,0.413793,0.190212,0.680587,438.861096,2316.025,8802.685,0.0023,0.0129,-0.0077,-0.0016,0.1032
167,1,17004,0.581,2.901,2.189,10.827,36.292,1392.0,0.431034,0.200276,0.754567,392.933484,2326.852,8838.977,-0.0002,-0.0137,0.0086,-0.0262,-0.2580
168,1,17016,0.606,3.092,2.573,11.869,37.196,1380.0,0.448276,0.195990,0.832147,441.479324,2338.721,8876.173,0.0021,0.0159,0.0320,0.0868,0.0753
169,1,17028,0.592,3.233,2.844,10.532,37.724,1368.0,0.465517,0.183112,0.879678,397.309168,2349.253,8913.897,-0.0012,0.0118,0.0226,-0.1114,0.0440
170,1,17040,0.580,3.018,2.346,10.824,38.607,1356.0,0.482759,0.192180,0.777336,417.882168,2360.077,8952.504,-0.0010,-0.0179,-0.0415,0.0243,0.0736
171,1,17052,0.618,3.345,2.939,11.068,37.682,1344.0,0.500000,0.184753,0.878625,417.064376,2371.145,8990.186,0.0032,0.0273,0.0494,0.0203,-0.0771
172,1,17064,0.602,3.003,3.180,11.647,39.278,1332.0,0.517241,0.200466,1.058941,457.470866,2382.792,9029.464,-0.0013,-0.0285,0.0201,0.0483,0.1330
173,1,17076,0.598,3.160,3.137,11.502,39.201,1320.0,0.534483,0.189240,0.992721,450.889902,2394.294,9068.665,-0.0003,0.0131,-0.0036,-0.0121,-0.0064
174,1,17088,0.599,3.323,3.521,11.739,38.473,1308.0,0.551724,0.180259,1.059584,451.634547,2406.033,9107.138,0.0001,0.0136,0.0320,0.0198,-0.0607
175,1,17100,0.602,3.470,3.405,11.387,38.903,1296.0,0.568966,0.173487,0.981268,442.988461,2417.420,9146.041,0.0003,0.0123,-0.0097,-0.0293,0.0358
176,1,17112,0.630,3.284,3.396,12.470,38.826,1284.0,0.586207,0.191839,1.034104,484.160220,2429.890,9184.867,0.0023,-0.0155,-0.0007,0.0903,-0.0064
177,1,17124,0.596,3.345,3.289,12.462,39.774,1272.0,0.603448,0.178176,0.983258,495.663588,2442.352,9224.641,-0.0028,0.0051,-0.0089,-0.0007,0.0790
178,1,17136,0.650,3.569,3.815,11.733,41.928,1260.0,0.620690,0.182124,1.068927,491.941224,2454.085,9266.569,0.0045,0.0187,0.0438,-0.0607,0.1795
179,1,17148,0.600,3.437,3.743,11.447,40.282,1248.0,0.637931,0.174571,1.089031,461.108054,2465.532,9306.851,-0.0042,-0.0110,-0.0060,-0.0238,-0.1372
180,1,17160,0.592,3.520,3.519,12.007,41.209,1236.0,0.655172,0.168182,0.999716,494.796463,2477.539,9348.060,-0.0007,0.0069,-0.0187,0.0467,0.0773
181,1,17172,0.632,3.702,4.034,11.682,40.230,1224.0,0.672414,0.170718,1.089681,469.966860,2489.221,9388.290,0.0033,0.0152,0.0429,-0.0271,-0.0816

In [6]:
X_cols = ['MODEL_ID', 'LIFT_AGE_HR', 'AGE_SINCE_LAST_MNT', 'ARM_DIST_mm', 'ARM_DIST_DELTA', 'DOOR_DIST_mm', 'DOOR_DIST_DELTA', 'FLOOR_DIST_mm', 'FLOOR_DIST_DELTA', 'FLOOR_DOOR_RATIO', 'ROPE_MFL_mV', 'ROPE_MFL_DELTA', 'ROPE_MFL_CUM', 'BEARING_TEMP_C', 'BEARING_TEMP_DELTA', 'BEARING_TEMP_CUM', 'TEMP_X_ROPE']

## data preprocessing

a few more preprocessing steps before we get to training:
* create training, validation, and testing splits
* scale the data so that the range isn't large
* then create sequences for an RNN to feed off of

In [7]:
from sklearn.preprocessing import StandardScaler

First create train/val/test splits in the ratio 70/15/15.

We avoid `train_test_split`, since each `lift_id` has a _contiguous_ time series of degradation. Taking random samples may cause misrepresentation. Instead, we simply take a continuous 70% of readings for each lift type to make the training set, and etc.

In [8]:
train_dfs = []
val_dfs = []
test_dfs = []

for lift_id, group in df_useful.groupby('MODEL_ID'):
    # Get the group's data
    group_data = group.reset_index(drop=True)
    n = len(group_data)

    # Calculate split indices for contiguous splits
    train_size = int(n * 0.7)
    val_size = int(n * 0.15)

    # Split contiguously (preserves temporal order)
    train_dfs.append(group_data[:train_size])
    val_dfs.append(group_data[train_size:train_size + val_size])
    test_dfs.append(group_data[train_size + val_size:])

# Concatenate all splits
train_df = pd.concat(train_dfs, ignore_index=True)
val_df = pd.concat(val_dfs, ignore_index=True)
test_df = pd.concat(test_dfs, ignore_index=True)

train_df.head(20)

,lift_id,lift_age_hours,ARM_DIST_mm,DOOR_DIST_mm,FLOOR_DIST_mm,ROPE_MFL_mV,BEARING_TEMP_C,RUL_hrs,age_since_last_maint,arm_door_ratio,floor_door_ratio,temp_x_rope,cumulative_rope_degradation,cumulative_bearing_heat,ARM_DIST_mm_per_hr,DOOR_DIST_mm_per_hr,FLOOR_DIST_mm_per_hr,ROPE_MFL_mV_per_hr,BEARING_TEMP_C_per_hr
0,1,16704,1.507,7.714,10.128,17.462,75.193,0.0,0.000000,0.195359,1.312937,1313.020166,2059.949,7925.487,0.0027,0.0016,0.0021,-0.1110,-0.0293
1,1,16716,0.492,2.087,0.079,9.907,33.291,1680.0,0.017241,0.235745,0.037853,329.813937,2069.856,7958.778,-0.0846,-0.4689,-0.8374,-0.6296,-3.4918
2,1,16728,0.483,2.071,0.005,10.555,34.098,1668.0,0.034483,0.233221,0.002414,359.904390,2080.411,7992.876,-0.0008,-0.0013,-0.0062,0.0540,0.0673
3,1,16740,0.540,2.087,0.322,10.248,35.311,1656.0,0.051724,0.258744,0.154288,361.867128,2090.659,8028.187,0.0048,0.0013,0.0264,-0.0256,0.1011
4,1,16752,0.528,2.177,0.241,10.670,34.296,1644.0,0.068966,0.242535,0.110703,365.938320,2101.329,8062.483,-0.0010,0.0075,-0.0068,0.0352,-0.0846
5,1,16764,0.528,2.187,0.183,10.131,35.045,1632.0,0.086207,0.241427,0.083676,355.040895,2111.460,8097.528,0.0000,0.0008,-0.0048,-0.0449,0.0624
6,1,16776,0.504,2.295,0.832,11.048,36.034,1620.0,0.103448,0.219608,0.362527,398.103632,2122.508,8133.562,-0.0020,0.0090,0.0541,0.0764,0.0824
7,1,16788,0.514,2.314,0.669,10.738,36.379,1608.0,0.120690,0.222126,0.289110,390.637702,2133.246,8169.941,0.0008,0.0016,-0.0136,-0.0258,0.0287
8,1,16800,0.502,2.294,0.672,11.244,34.894,1596.0,0.137931,0.218832,0.292938,392.348136,2144.490,8204.835,-0.0010,-0.0017,0.0003,0.0422,-0.1237
9,1,16812,0.538,2.218,0.837,10.575,35.182,1584.0,0.155172,0.242561,0.377367,372.049650,2155.065,8240.017,0.0030,-0.0063,0.0137,-0.0558,0.0240
10,1,16824,0.520,2.404,1.001,11.080,36.504,1572.0,0.172414,0.216306,0.416389,404.464320,2166.145,8276.521,-0.0015,0.0155,0.0137,0.0421,0.1102
11,1,16836,0.530,2.569,1.466,10.198,36.328,1560.0,0.189655,0.206306,0.570650,370.472944,2176.343,8312.849,0.0008,0.0138,0.0388,-0.0735,-0.0147
12,1,16848,0.568,2.633,1.085,10.417,38.096,1548.0,0.206897,0.215723,0.412077,396.846032,2186.760,8350.945,0.0032,0.0053,-0.0318,0.0182,0.1473
13,1,16860,0.563,2.393,1.380,10.226,34.926,1536.0,0.224138,0.235269,0.576682,357.153276,2196.986,8385.871,-0.0004,-0.0200,0.0246,-0.0159,-0.2642
14,1,16872,0.581,2.426,1.376,10.951,37.216,1524.0,0.241379,0.239489,0.567189,407.552416,2207.937,8423.087,0.0015,0.0028,-0.0003,0.0604,0.1908
15,1,16884,0.530,2.659,1.515,10.196,37.595,1512.0,0.258621,0.199323,0.569763,383.318620,2218.133,8460.682,-0.0042,0.0194,0.0116,-0.0629,0.0316
16,1,16896,0.562,2.575,1.462,9.856,38.828,1500.0,0.275862,0.218252,0.567767,382.688768,2227.989,8499.510,0.0027,-0.0070,-0.0044,-0.0283,0.1028
17,1,16908,0.560,2.554,1.722,11.137,36.307,1488.0,0.293103,0.219264,0.674236,404.351059,2239.126,8535.817,-0.0002,-0.0018,0.0217,0.1068,-0.2101
18,1,16920,0.553,2.681,1.798,10.254,40.348,1476.0,0.310345,0.206266,0.670645,413.728392,2249.380,8576.165,-0.0006,0.0106,0.0063,-0.0736,0.3367
19,1,16932,0.574,2.663,1.748,10.407,38.214,1464.0,0.327586,0.215546,0.656402,397.693098,2259.787,8614.379,0.0017,-0.0015,-0.0042,0.0128,-0.1778

Then scale the data with `StandardScaler`.

In [9]:
scaler = StandardScaler()
train_df[X_cols] = scaler.fit_transform(train_df[X_cols])
val_df[X_cols] = scaler.transform(val_df[X_cols])
test_df[X_cols] = scaler.transform(test_df[X_cols])

Lastly, create sequences for training with an RNN.

In [10]:
def create_seqs(data, seq_len, feature_cols, target_col="RUL_HR"):
    X, y = [], []

    # Create sequences within each lift separately
    for lift_id, group in data.groupby('LIFT_ID'):
        features = group[feature_cols].values
        targets = group[target_col].values

        for i in range(len(group) - seq_len):
            X.append(features[i : i + seq_len])
            y.append(targets[i + seq_len])
    return np.array(X), np.array(y)


X_train, y_train = create_seqs(train_df, seq_len=50, feature_cols=X_cols)
X_val, y_val = create_seqs(val_df, seq_len=50, feature_cols=X_cols)
X_test, y_test = create_seqs(test_df, seq_len=50, feature_cols=X_cols)

## build an LSTM!
We use `pytorch_lightning` to build an LSTM and then train it on the datasets created.

In [12]:
!pip install torchmetrics pytorch_lightning weave wandb

import os

# The essentials
import torch
import torchmetrics as tm
import torch.nn as nn
import pytorch_lightning as pl
from torch.utils.data import DataLoader, TensorDataset

# For logging
import weave
import wandb

Requirement already satisfied: torchmetrics in /usr/local/lib/python3.12/dist-packages (1.9.0)
Requirement already satisfied: pytorch_lightning in /usr/local/lib/python3.12/dist-packages (2.6.5)
Requirement already satisfied: weave in /usr/local/lib/python3.12/dist-packages (0.52.42)
Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (0.27.1)
Requirement already satisfied: numpy>1.20.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.0.2)
Requirement already satisfied: packaging>17.1 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (26.2)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.11.0+cu128)
Requirement already satisfied: lightning-utilities>=0.15.3 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (0.15.3)
Requirement already satisfied: tqdm>=4.57.0 in /usr/local/lib/python3.12/dist-packages (from pytorch_lightning) (4.67.3)
Requirement already satisfied: PyYAML>5.4 in /usr/local/lib/python3.12/dist-packages (from pytorch_lightning) (6.0.3)
Requirement already satisfied: fsspec>=2022.5.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2022.5.0->pytorch_lightning) (2025.3.0)
Requirement already satisfied: typing-extensions>4.5.0 in /usr/local/lib/python3.12/dist-packages (from pytorch_lightning) (4.15.0)
Requirement already satisfied: cachetools>=6.2.4 in /usr/local/lib/python3.12/dist-packages (from weave) (6.2.6)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from weave) (8.4.1)
Requirement already satisfied: diskcache-weave==5.6.3.post1 in /usr/local/lib/python3.12/dist-packages (from weave) (5.6.3.post1)
Requirement already satisfied: gql>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[httpx]>=3.0.0->weave) (4.0.0)
Requirement already satisfied: jsonschema>=4.23.0 in /usr/local/lib/python3.12/dist-packages (from weave) (4.26.0)
Requirement already satisfied: opentelemetry-api>=1.28.0 in /usr/local/lib/python3.12/dist-packages (from weave) (1.42.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-http>=1.28.0 in /usr/local/lib/python3.12/dist-packages (from weave) (1.42.1)
Requirement already satisfied: opentelemetry-sdk>=1.28.0 in /usr/local/lib/python3.12/dist-packages (from weave) (1.42.1)
Requirement already satisfied: opentelemetry-semantic-conventions>=0.63b0 in /usr/local/lib/python3.12/dist-packages (from weave) (0.63b1)
Requirement already satisfied: polyfile-weave>=0.5.9 in /usr/local/lib/python3.12/dist-packages (from weave) (0.5.9)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from weave) (2.12.3)
Requirement already satisfied: sentry-sdk<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from weave) (2.61.1)
Requirement already satisfied: tenacity!=8.4.0,>=8.3.0 in /usr/local/lib/python3.12/dist-packages (from weave) (9.1.4)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (3.1.50)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb) (4.10.0)
Requirement already satisfied: protobuf!=5.28.0,!=5.29.0,<8,>4.21.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (5.29.6)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.32.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2022.5.0->pytorch_lightning) (3.14.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: graphql-core<3.3,>=3.2 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (3.2.11)
Requirement already satisfied: yarl<2.0,>=1.6 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (1.24.2)
Requirement already satisfied: backoff<3.0,>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (2.2.1)
Requirement already satisfied: anyio<5,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (4.13.0)
Requirement already satisfied: httpx<1,>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from gql[httpx]>=3.0.0->weave) (0.28.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (2026.5.1)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-http>=1.28.0->weave) (1.75.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.42.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-http>=1.28.0->weave) (1.42.1)
Requirement already satisfied: opentelemetry-proto==1.42.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-http>=1.28.0->weave) (1.42.1)
Requirement already satisfied: abnf~=2.2.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (2.2.0)
Requirement already satisfied: chardet>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (5.2.0)
Requirement already satisfied: cint>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (1.0.0)
Requirement already satisfied: fickling>=0.0.8 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (0.1.11)
Requirement already satisfied: filelock>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.29.1)
Requirement already satisfied: graphviz>=0.20.1 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (0.21)
Requirement already satisfied: intervaltree>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.2.1)
Requirement already satisfied: jinja2>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.1.6)
Requirement already satisfied: kaitaistruct>=0.11 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (0.11)
Requirement already satisfied: networkx>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.6.1)
Requirement already satisfied: Pillow>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (11.3.0)
Requirement already satisfied: pdfminer.six>=20251230 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (20260107)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->weave) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->weave) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->weave) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2026.5.20)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (1.14.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.90)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (0.5.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->torchmetrics) (1.5.5)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.27.0->gql[httpx]>=3.0.0->weave) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.27.0->gql[httpx]>=3.0.0->weave) (0.16.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from intervaltree>=2.4.0->polyfile-weave>=0.5.9->weave) (2.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.1.0->polyfile-weave>=0.5.9->weave) (3.0.3)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (48.0.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->torchmetrics) (1.3.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (3.0)

In [13]:
# Some important constants
BATCH_SIZE = 32
N_EPOCHS = 25
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-5
DROPOUT = 0.2
MODEL_DIR = os.path.join(os.getcwd(), "lightning_logs/checkpoints/")

We first create the appropriate datasets and dataloaders, using `TensorDataset` and `DataLoader`.

In [14]:
# create datasets and dataloaders
train_dataset = TensorDataset(
    torch.tensor(X_train, dtype=torch.float32),
    torch.tensor(y_train, dtype=torch.float32),
)
val_dataset = TensorDataset(
    torch.tensor(X_val, dtype=torch.float32), torch.tensor(y_val, dtype=torch.float32)
)
test_dataset = TensorDataset(
    torch.tensor(X_test, dtype=torch.float32), torch.tensor(y_test, dtype=torch.float32)
)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE)

Define an overarching LSTM class, complete with
- training, validation, and testing steps
- model metrics logged
- initialisation of callbacks and trainer objects

In [15]:
class BasicLSTM(pl.LightningModule):
    """A simple LSTM-based regression model for RUL prediction.
    All subsequent models will use this class as a parent."""
    def __init__(
        self,
        input_size: int = X_train.shape[2],
        output_size: int = 1,
        lr: float = LEARNING_RATE,
        weight_decay: float = WEIGHT_DECAY,
        dropout: float = DROPOUT,
    ):
        super(BasicLSTM, self).__init__()
        self.save_hyperparameters()
        torch.set_float32_matmul_precision("high")

        self.lstm1 = nn.LSTM(input_size, 128, num_layers=1, batch_first=True)
        self.dropout_layer = nn.Dropout(p=self.hparams.dropout)
        self.lstm2 = nn.LSTM(128, 64, num_layers=1, batch_first=True)
        self.fc = nn.Linear(64, output_size)
        self.criterion = nn.MSELoss()

        # assess a few more metrics
        self.mae = tm.MeanAbsoluteError()
        self.r2 = tm.R2Score()
        self.train_mae = self.mae.clone()
        self.val_mae = self.mae.clone()
        self.test_mae = self.mae.clone()
        self.train_r2 = self.r2.clone()
        self.val_r2 = self.r2.clone()
        self.test_r2 = self.r2.clone()

    def forward(self, x):
        out, _ = self.lstm1(x)
        out = self.dropout_layer(out)
        out, _ = self.lstm2(out)
        out = self.fc(out[:, -1, :])
        return out.squeeze(-1)

    def _shared_step(self, batch):
        x, y = batch
        y_hat = self(x)
        loss = self.criterion(y_hat, y.float())
        return loss, y, y_hat

    def training_step(self, batch, batch_idx):
        loss, truths, preds = self._shared_step(batch)
        self.log("train_loss", loss, on_step=False, on_epoch=True, prog_bar=True)
        mae = self.train_mae(preds, truths.float())
        r2 = self.train_r2(preds, truths.float())
        self.log("train_mae", mae, on_step=False, on_epoch=True, prog_bar=True)
        self.log("train_r2", r2, on_step=False, on_epoch=True, prog_bar=True)
        return loss

    def validation_step(self, batch, batch_idx):
        loss, truths, preds = self._shared_step(batch)
        self.log("val_loss", loss, on_step=False, on_epoch=True, prog_bar=True)
        mae = self.val_mae(preds, truths.float())
        r2 = self.val_r2(preds, truths.float())
        self.log("val_mae", mae, on_step=False, on_epoch=True, prog_bar=True)
        self.log("val_r2", r2, on_step=False, on_epoch=True, prog_bar=True)
        return loss

    def test_step(self, batch, batch_idx):
        loss, truths, preds = self._shared_step(batch)
        self.log("test_loss", loss, on_step=False, on_epoch=True, prog_bar=True)
        mae = self.test_mae(preds, truths.float())
        r2 = self.test_r2(preds, truths.float())
        self.log("test_mae", mae, on_step=False, on_epoch=True, prog_bar=True)
        self.log("test_r2", r2, on_step=False, on_epoch=True, prog_bar=True)
        return loss

    def get_callbacks(self, tnow=None, model_name=None):
        early_stop = pl.callbacks.EarlyStopping(
            monitor="val_loss", patience=5, mode="min", verbose=True,
        )
        checkpoint = pl.callbacks.ModelCheckpoint(
            monitor="val_loss",
            dirpath=f"checkpoints/{model_name}_{tnow}",
            filename="{epoch:02d}-{val_loss:.4f}",
            save_top_k=1,
            mode="min",
            verbose=True,
        )
        lr_monitor = pl.callbacks.LearningRateMonitor(logging_interval="epoch")
        return [early_stop, checkpoint, lr_monitor]

    def get_trainer(self, max_epochs: int, callbacks=None, timestamp=None):
        logger = pl.loggers.WandbLogger(project="zeleo")
        return pl.Trainer(
            max_epochs=max_epochs,
            callbacks=callbacks,
            accelerator="auto",
            devices="auto",
            log_every_n_steps=100,
            logger=logger,
            gradient_clip_val=1.0,
            deterministic=False,
            precision="16-mixed" if torch.cuda.is_available() else "32",
        )

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(
            self.parameters(),
            lr=self.hparams.lr,
            weight_decay=self.hparams.weight_decay,
        )
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode="min", factor=0.5, patience=3
        )
        return {
            "optimizer": optimizer,
            "lr_scheduler": {
                "scheduler": scheduler,
                "monitor": "val_loss",
                "interval": "epoch",
                "frequency": 1,
            },
        }

Then we can embark on **training the model**!

In [16]:
now = datetime.now().strftime("%Y%m%d-%H%M")
callbacks = model.get_callbacks(tnow=now, model_name="BasicLSTM")
trainer = model.get_trainer(max_epochs=N_EPOCHS, callbacks=callbacks, timestamp=now)
trainer.fit(model, train_loader, val_loader)

INFO:pytorch_lightning.utilities.rank_zero:Using 16bit Automatic Mixed Precision (AMP)
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
wandb: WARNING The anonymous setting has no effect and will be removed in a future version.
/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: jiyometrik (huomi) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

wandb: Initializing weave.
weave: Logged in as Weights & Biases user: jiyometrik.
weave: View Weave data at https://wandb.ai/huomi/zeleo/weave
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/model_summary/model_summary.py:242: Precision 16-mixed is not supported by the model summary.  Estimated model size in MB will not be accurate. Using 32 bits instead.

┏━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name          ┃ Type              ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ lstm1         │ LSTM              │ 75.8 K │ train │     0 │
│ 1  │ dropout_layer │ Dropout           │      0 │ train │     0 │
│ 2  │ lstm2         │ LSTM              │ 49.7 K │ train │     0 │
│ 3  │ fc            │ Linear            │     65 │ train │     0 │
│ 4  │ criterion     │ MSELoss           │      0 │ train │     0 │
│ 5  │ mae           │ MeanAbsoluteError │      0 │ train │     0 │
│ 6  │ r2            │ R2Score           │      0 │ train │     0 │
│ 7  │ train_mae     │ MeanAbsoluteError │      0 │ train │     0 │
│ 8  │ val_mae       │ MeanAbsoluteError │      0 │ train │     0 │
│ 9  │ test_mae      │ MeanAbsoluteError │      0 │ train │     0 │
│ 10 │ train_r2      │ R2Score           │      0 │ train │     0 │
│ 11 │ val_r2        │ R2Score           │      0 │ train │     0 │
│ 12 │ test_r2       │ R2Score           │      0 │ train │     0 │
└────┴───────────────┴───────────────────┴────────┴───────┴───────┘

Trainable params: 125 K
Non-trainable params: 0
Total params: 125 K
Total estimated model params size (MB): 0.502
Modules in train mode: 13
Modules in eval mode: 0
Total FLOPs: 0

Output()

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)`
is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved. New best score: 631048.312
INFO:pytorch_lightning.utilities.rank_zero:Epoch 0, global step 1294: 'val_loss' reached 631048.31250 (best 631048.31250), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=00-val_loss=631048.3125.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 101993.875 >= min_delta = 0.0. New best score: 529054.438
INFO:pytorch_lightning.utilities.rank_zero:Epoch 1, global step 2588: 'val_loss' reached 529054.43750 (best 529054.43750), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=01-val_loss=529054.4375.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 87921.625 >= min_delta = 0.0. New best score: 441132.812
INFO:pytorch_lightning.utilities.rank_zero:Epoch 2, global step 3882: 'val_loss' reached 441132.81250 (best 441132.81250), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=02-val_loss=441132.8125.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 73172.688 >= min_delta = 0.0. New best score: 367960.125
INFO:pytorch_lightning.utilities.rank_zero:Epoch 3, global step 5176: 'val_loss' reached 367960.12500 (best 367960.12500), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=03-val_loss=367960.1250.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 50873.000 >= min_delta = 0.0. New best score: 317087.125
INFO:pytorch_lightning.utilities.rank_zero:Epoch 4, global step 6470: 'val_loss' reached 317087.12500 (best 317087.12500), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=04-val_loss=317087.1250.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 47748.469 >= min_delta = 0.0. New best score: 269338.656
INFO:pytorch_lightning.utilities.rank_zero:Epoch 5, global step 7764: 'val_loss' reached 269338.65625 (best 269338.65625), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=05-val_loss=269338.6562.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 48623.578 >= min_delta = 0.0. New best score: 220715.078
INFO:pytorch_lightning.utilities.rank_zero:Epoch 6, global step 9058: 'val_loss' reached 220715.07812 (best 220715.07812), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=06-val_loss=220715.0781.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 43152.844 >= min_delta = 0.0. New best score: 177562.234
INFO:pytorch_lightning.utilities.rank_zero:Epoch 7, global step 10352: 'val_loss' reached 177562.23438 (best 177562.23438), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=07-val_loss=177562.2344.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 34828.344 >= min_delta = 0.0. New best score: 142733.891
INFO:pytorch_lightning.utilities.rank_zero:Epoch 8, global step 11646: 'val_loss' reached 142733.89062 (best 142733.89062), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=08-val_loss=142733.8906.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 28848.625 >= min_delta = 0.0. New best score: 113885.266
INFO:pytorch_lightning.utilities.rank_zero:Epoch 9, global step 12940: 'val_loss' reached 113885.26562 (best 113885.26562), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=09-val_loss=113885.2656.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 23521.797 >= min_delta = 0.0. New best score: 90363.469
INFO:pytorch_lightning.utilities.rank_zero:Epoch 10, global step 14234: 'val_loss' reached 90363.46875 (best 90363.46875), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=10-val_loss=90363.4688.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 18158.609 >= min_delta = 0.0. New best score: 72204.859
INFO:pytorch_lightning.utilities.rank_zero:Epoch 11, global step 15528: 'val_loss' reached 72204.85938 (best 72204.85938), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=11-val_loss=72204.8594.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 13517.582 >= min_delta = 0.0. New best score: 58687.277
INFO:pytorch_lightning.utilities.rank_zero:Epoch 12, global step 16822: 'val_loss' reached 58687.27734 (best 58687.27734), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=12-val_loss=58687.2773.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 11561.887 >= min_delta = 0.0. New best score: 47125.391
INFO:pytorch_lightning.utilities.rank_zero:Epoch 13, global step 18116: 'val_loss' reached 47125.39062 (best 47125.39062), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=13-val_loss=47125.3906.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 8560.992 >= min_delta = 0.0. New best score: 38564.398
INFO:pytorch_lightning.utilities.rank_zero:Epoch 14, global step 19410: 'val_loss' reached 38564.39844 (best 38564.39844), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=14-val_loss=38564.3984.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 5556.684 >= min_delta = 0.0. New best score: 33007.715
INFO:pytorch_lightning.utilities.rank_zero:Epoch 15, global step 20704: 'val_loss' reached 33007.71484 (best 33007.71484), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=15-val_loss=33007.7148.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 4924.330 >= min_delta = 0.0. New best score: 28083.385
INFO:pytorch_lightning.utilities.rank_zero:Epoch 16, global step 21998: 'val_loss' reached 28083.38477 (best 28083.38477), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=16-val_loss=28083.3848.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 4586.357 >= min_delta = 0.0. New best score: 23497.027
INFO:pytorch_lightning.utilities.rank_zero:Epoch 17, global step 23292: 'val_loss' reached 23497.02734 (best 23497.02734), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=17-val_loss=23497.0273.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 3403.982 >= min_delta = 0.0. New best score: 20093.045
INFO:pytorch_lightning.utilities.rank_zero:Epoch 18, global step 24586: 'val_loss' reached 20093.04492 (best 20093.04492), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=18-val_loss=20093.0449.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 1429.223 >= min_delta = 0.0. New best score: 18663.822
INFO:pytorch_lightning.utilities.rank_zero:Epoch 19, global step 25880: 'val_loss' reached 18663.82227 (best 18663.82227), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=19-val_loss=18663.8223.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 1823.146 >= min_delta = 0.0. New best score: 16840.676
INFO:pytorch_lightning.utilities.rank_zero:Epoch 20, global step 27174: 'val_loss' reached 16840.67578 (best 16840.67578), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=20-val_loss=16840.6758.ckpt' as top 1
INFO:pytorch_lightning.utilities.rank_zero:Epoch 21, global step 28468: 'val_loss' was not in top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 983.343 >= min_delta = 0.0. New best score: 15857.333
INFO:pytorch_lightning.utilities.rank_zero:Epoch 22, global step 29762: 'val_loss' reached 15857.33301 (best 15857.33301), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=22-val_loss=15857.3330.ckpt' as top 1
INFO:pytorch_lightning.utilities.rank_zero:Epoch 23, global step 31056: 'val_loss' was not in top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 344.258 >= min_delta = 0.0. New best score: 15513.075
INFO:pytorch_lightning.utilities.rank_zero:Epoch 24, global step 32350: 'val_loss' reached 15513.07520 (best 15513.07520), saving model to '/content/checkpoints/BasicLSTM_20260612-0208/epoch=24-val_loss=15513.0752.ckpt' as top 1
INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=25` reached.

Finally, test the model.

In [17]:
results = trainer.test(model, test_loader, ckpt_path="best")
test_mae = np.round(results[0]["test_mae"], 4)
test_mae_days = np.round(test_mae / 24, 4)

print(f"*** DONE !!! ***")
print(f"*** test_mae = {test_mae} hours = {test_mae_days} days")
wandb.finish()

INFO:pytorch_lightning.utilities.rank_zero:Restoring states from the checkpoint path at /content/checkpoints/BasicLSTM_20260612-0208/epoch=24-val_loss=15513.0752.ckpt
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.utilities.rank_zero:Loaded model weights from the checkpoint at /content/checkpoints/BasicLSTM_20260612-0208/epoch=24-val_loss=15513.0752.ckpt

Output()

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_loss         │      23887.732421875      │
│         test_mae          │     98.17897033691406     │
│          test_r2          │    0.12922509014606476    │
└───────────────────────────┴───────────────────────────┘

*** DONE !!! ***
*** test_mae = 98.179 hours = 4.0908 days

## refine the lstm

Implement another LSTM with a convolutional layer first, as well as an attention mechanism.

In [ ]:
class JiyoAttention(nn.Module):
    def __init__(self, hidden_size):
        super().__init__()
        self.attn = nn.Linear(hidden_size, 1)

    def forward(self, out):
        weights = torch.softmax(self.attn(out), dim=1)
        ctx = (weights * out).sum(dim=1)
        return ctx, weights


class JiyoLSTM(BasicLSTM):
    """A modified version of the LSTM structure, with convolutional layers and
    an attention mechanism"""

    def __init__(self, ):
        super(JiyoLSTM, self).__init__()#input_size, output_size, lr, dropout, weight_decay)
        self.save_hyperparameters()
        self.drop_p = .25

        # Specify a convolutional layer first
        self.conv = nn.Conv1d(
            in_channels=X_train.shape[2],
            out_channels=32,
            kernel_size=5,
            padding=5//2,
        )
        self.conv_drop = nn.Dropout(p=self.drop_p)

        # Then the remaining LSTM layers
        self.lstm = nn.LSTM(32, 128, num_layers=2, batch_first=True, dropout=self.drop_p)
        self.attention = JiyoAttention(128)

        # and finally the classifier
        self.fc1 = nn.Linear(128, 32)
        self.fc2 = nn.Linear(32, 1)
        self.fc_drop = nn.Dropout(p=self.drop_p)
        self.criterion = nn.MSELoss()


    def forward(self, x):
        # CNN expects multi-dim input
        out = x.permute(0, 2, 1)
        out = self.conv(out)
        out = torch.relu(out)
        out = self.dropout_layer(out)
        out = out.permute(0, 2, 1)

        # LSTM + Attn
        out, _ = self.lstm(out)
        out, attention_weights = self.attention(out)

        # classifier
        out = torch.relu(self.fc1(out))
        out = self.fc2(self.fc_drop(out))

        return out.squeeze(-1), attention_weights

    def get_attention_weights(self, dl: DataLoader):
        """
        Utility function to extract feature importances via attention weights.
        This only works for JiyoLSTM and derivatives, not BasicLSTM.
        """
        self.eval()
        all_weights = []
        with torch.no_grad():
            for x, _ in dl:
                x = x.to(self.device)
                _ = self.forward(x)  # forward pass to compute attention weights
                _, attention_weights = self.attention(self.lstm(x)[0])
                all_weights.append(attention_weights.cpu().numpy())

        return np.concatenate(all_weights, axis=0)

In [19]:
jiyomodel = JiyoLSTM()
jiyonow = datetime.now().strftime("%Y%m%d-%H%M")
callbacks = jiyomodel.get_callbacks(tnow=jiyonow, model_name="JiyoLSTM")
jiyotrainer = jiyomodel.get_trainer(max_epochs=N_EPOCHS, callbacks=callbacks, timestamp=jiyonow)
jiyotrainer.fit(jiyomodel, train_loader, val_loader)

INFO:pytorch_lightning.utilities.rank_zero:Using 16bit Automatic Mixed Precision (AMP)
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

wandb: Initializing weave.

Output()

weave: Logged in as Weights & Biases user: jiyometrik.
weave: View Weave data at https://wandb.ai/huomi/zeleo/weave
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/model_summary/model_summary.py:242: Precision 16-mixed is not supported by the model summary.  Estimated model size in MB will not be accurate. Using 32 bits instead.

┏━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name          ┃ Type              ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ lstm1         │ LSTM              │ 75.8 K │ train │     0 │
│ 1  │ dropout_layer │ Dropout           │      0 │ train │     0 │
│ 2  │ lstm2         │ LSTM              │ 49.7 K │ train │     0 │
│ 3  │ fc            │ Linear            │     65 │ train │     0 │
│ 4  │ criterion     │ MSELoss           │      0 │ train │     0 │
│ 5  │ mae           │ MeanAbsoluteError │      0 │ train │     0 │
│ 6  │ r2            │ R2Score           │      0 │ train │     0 │
│ 7  │ train_mae     │ MeanAbsoluteError │      0 │ train │     0 │
│ 8  │ val_mae       │ MeanAbsoluteError │      0 │ train │     0 │
│ 9  │ test_mae      │ MeanAbsoluteError │      0 │ train │     0 │
│ 10 │ train_r2      │ R2Score           │      0 │ train │     0 │
│ 11 │ val_r2        │ R2Score           │      0 │ train │     0 │
│ 12 │ test_r2       │ R2Score           │      0 │ train │     0 │
│ 13 │ conv          │ Conv1d            │  2.9 K │ train │     0 │
│ 14 │ conv_drop     │ Dropout           │      0 │ train │     0 │
│ 15 │ lstm          │ LSTM              │  215 K │ train │     0 │
│ 16 │ attention     │ JiyoAttention     │    129 │ train │     0 │
│ 17 │ fc1           │ Linear            │  4.1 K │ train │     0 │
│ 18 │ fc2           │ Linear            │     33 │ train │     0 │
│ 19 │ fc_drop       │ Dropout           │      0 │ train │     0 │
└────┴───────────────┴───────────────────┴────────┴───────┴───────┘

Trainable params: 347 K
Non-trainable params: 0
Total params: 347 K
Total estimated model params size (MB): 1.391
Modules in train mode: 21
Modules in eval mode: 0
Total FLOPs: 0

Output()

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)`
is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved. New best score: 39383.750
INFO:pytorch_lightning.utilities.rank_zero:Epoch 0, global step 1294: 'val_loss' reached 39383.75000 (best 39383.75000), saving model to '/content/checkpoints/JiyoLSTM_20260612-0225/epoch=00-val_loss=39383.7500.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 9619.414 >= min_delta = 0.0. New best score: 29764.336
INFO:pytorch_lightning.utilities.rank_zero:Epoch 1, global step 2588: 'val_loss' reached 29764.33594 (best 29764.33594), saving model to '/content/checkpoints/JiyoLSTM_20260612-0225/epoch=01-val_loss=29764.3359.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 1235.273 >= min_delta = 0.0. New best score: 28529.062
INFO:pytorch_lightning.utilities.rank_zero:Epoch 2, global step 3882: 'val_loss' reached 28529.06250 (best 28529.06250), saving model to '/content/checkpoints/JiyoLSTM_20260612-0225/epoch=02-val_loss=28529.0625.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 159.922 >= min_delta = 0.0. New best score: 28369.141
INFO:pytorch_lightning.utilities.rank_zero:Epoch 3, global step 5176: 'val_loss' reached 28369.14062 (best 28369.14062), saving model to '/content/checkpoints/JiyoLSTM_20260612-0225/epoch=03-val_loss=28369.1406.ckpt' as top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 3033.496 >= min_delta = 0.0. New best score: 25335.645
INFO:pytorch_lightning.utilities.rank_zero:Epoch 4, global step 6470: 'val_loss' reached 25335.64453 (best 25335.64453), saving model to '/content/checkpoints/JiyoLSTM_20260612-0225/epoch=04-val_loss=25335.6445.ckpt' as top 1
INFO:pytorch_lightning.utilities.rank_zero:Epoch 5, global step 7764: 'val_loss' was not in top 1
INFO:pytorch_lightning.callbacks.early_stopping:Metric val_loss improved by 121.676 >= min_delta = 0.0. New best score: 25213.969
INFO:pytorch_lightning.utilities.rank_zero:Epoch 6, global step 9058: 'val_loss' reached 25213.96875 (best 25213.96875), saving model to '/content/checkpoints/JiyoLSTM_20260612-0225/epoch=06-val_loss=25213.9688.ckpt' as top 1
INFO:pytorch_lightning.utilities.rank_zero:Epoch 7, global step 10352: 'val_loss' was not in top 1
INFO:pytorch_lightning.utilities.rank_zero:Epoch 8, global step 11646: 'val_loss' was not in top 1
INFO:pytorch_lightning.utilities.rank_zero:Epoch 9, global step 12940: 'val_loss' was not in top 1
INFO:pytorch_lightning.utilities.rank_zero:Epoch 10, global step 14234: 'val_loss' was not in top 1
INFO:pytorch_lightning.callbacks.early_stopping:Monitored metric val_loss did not improve in the last 5 records. Best score: 25213.969. Signaling Trainer to stop.
INFO:pytorch_lightning.utilities.rank_zero:Epoch 11, global step 15528: 'val_loss' was not in top 1

In [20]:
jiyoresults = jiyotrainer.test(jiyomodel, test_loader, ckpt_path="best")
jiyotest_mae = np.round(jiyoresults[0]["test_mae"], 4)
jiyotest_mae_days = np.round(jiyotest_mae / 24, 4)

print(f"*** DONE !!! ***")
print(f"*** test_mae = {jiyotest_mae} hours = {jiyotest_mae_days} days")
wandb.finish()

INFO:pytorch_lightning.utilities.rank_zero:Restoring states from the checkpoint path at /content/checkpoints/JiyoLSTM_20260612-0225/epoch=06-val_loss=25213.9688.ckpt
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.utilities.rank_zero:Loaded model weights from the checkpoint at /content/checkpoints/JiyoLSTM_20260612-0225/epoch=06-val_loss=25213.9688.ckpt

Output()

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_loss         │       29847.890625        │
│         test_mae          │     95.01197052001953     │
│          test_r2          │    0.3719482719898224     │
└───────────────────────────┴───────────────────────────┘

*** DONE !!! ***
*** test_mae = 95.012 hours = 3.9588 days

We can also extract the feature importances via the `JiyoLSTM` attention weights.

In [ ]:
print("*** Getting attention weights...")
attn_weights = jiyomodel.get_attention_weights(dl=test_loader)
avg_feature_importance = attn_weights.squeeze(-1).mean(axis=0)
sns.heatmap(avg_feature_importance.reshape(1, -1), annot=True, yticklabels=["feature importance"], xticklabels=X_cols).set(title="JiyoLSTM average attention weights per feature")
plt.ylabel("feature")
plt.xlabel("weight")